FROM node:20.3.1-alpine3.17

WORKDIR /usr/src/app
COPY package*.json ./

CMD npm ci && \
    npx wait-port metadata:80 && \
    npx wait-port history:80 && \
    npx wait-port video-streaming:80 && \
    npm run start:dev
